/*
 * English Dependencies Demo Project
 * Author: jcyuyi@gmail.com
 */

package NLPEnglishEditor;

import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;


public class NLPDependencyPanel extends javax.swing.JPanel {

    DepTableModel tableModel;
    NLPEntry entry;
    NLPEntry oldEntry;
    MainFrame parentFrame;
    /**
     * Creates new form NLPDependencyPanel
     */
    public NLPDependencyPanel() {
        initComponents();
        setDependencies(new NLPEntry());
    }
    
    public void setParentFrame(MainFrame f) {
        parentFrame = f;
    }
    
    public void setDependencies(NLPEntry aEntry) {
        oldEntry = new NLPEntry(aEntry);
        entry =  aEntry;
        tableModel = new DepTableModel();
        tableModel.addDependencies(aEntry.getDependency());
        depTable.setModel(tableModel);
        
        TableColumn relnCol = depTable.getColumnModel().getColumn(0);
        JComboBox comboBox = new JComboBox();
        List<String> relns = NLPSettings.getDependencyStrings();
        for (String reln : relns) {
            comboBox.addItem(reln);
        }
        relnCol.setCellEditor(new DefaultCellEditor(comboBox));
        
        TableColumn govCol = depTable.getColumnModel().getColumn(1);
        TableColumn depCol = depTable.getColumnModel().getColumn(2);
        comboBox = new JComboBox();
        comboBox.addItem("ROOT-0");
        for (int i = 0; i < aEntry.getWords().size(); i++) {
            comboBox.addItem(aEntry.getWords().get(i));
        }
        govCol.setCellEditor(new DefaultCellEditor(comboBox));
        depCol.setCellEditor(new DefaultCellEditor(comboBox));
    }

    class DepTableModel extends AbstractTableModel {
        private List<NLPDependency> deps;
        private final String[] columnNames = {"Reln","Gov","Dep"};
        public void addDependencies(List<NLPDependency> aDeps) {
            deps = aDeps;
        }
        @Override
        public int getColumnCount() {
            return columnNames.length;
        }
        @Override
        public int getRowCount() {
            return deps.size();
        }
        @Override
        public String getColumnName(int col) {
            return columnNames[col];
        }
        @Override
        public Object getValueAt (int row, int col)
        {
            String colName = getColumnName(col);
            switch (colName) {

                case "Reln":
                    return deps.get(row).getReln();
                case "Gov":
                    return deps.get(row).getGov();
                case "Dep":
                    return deps.get(row).getDep();
                default:
                    return "ERROR";
            }
                    
        }
        @Override
        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }
        @Override
        public boolean isCellEditable(int row,int col) {
            return true;
        }
        @Override
        public void setValueAt(Object value, int row, int col) {
            String colName = getColumnName(col);
            switch (colName) {
                case "Reln":
                    deps.get(row).setReln((String)value);
                    break;
                case "Gov":
                    deps.get(row).setGov((String)value);
                    break;
                case "Dep":
                    deps.get(row).setDep((String)value);
                    break;
                default:
                    
            }
            fireTableCellUpdated(row, col); //redraw
        }
        
        public void addNewItem() {
            deps.add(new NLPDependency());
            fireTableRowsInserted(deps.size() - 1, deps.size());
        }
        
        public void removeRow(int row) {
            deps.remove(row);
            fireTableRowsDeleted(row,row);
        }
    }
    
    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        NLPDependencyPanel panel = new NLPDependencyPanel();
        NLPParser p = new NLPParser("This is a test!");
        NLPEntry e = new NLPEntry();
        e.setDependency(p.getDependencyList());
        e.setWords(p.getRawStringWords());
        panel.setDependencies(e);
        f.add(panel);
        f.setSize(800, 600);
        f.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        depTable = new javax.swing.JTable();
        btnApply = new javax.swing.JButton();
        btnDiscard = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        depTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(depTable);

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnDiscard.setText("Discard");
        btnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Dependency Edit:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                        .addComponent(btnDiscard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnDiscard)
                    .addComponent(btnApply)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        tableModel.addNewItem();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int sel = depTable.getSelectedRow();
        if (sel >= 0) {
            tableModel.removeRow(sel);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardActionPerformed
        setDependencies(oldEntry);
    }//GEN-LAST:event_btnDiscardActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        if (parentFrame != null) {
            parentFrame.setNewDependency(entry);
        }
    }//GEN-LAST:event_btnApplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDiscard;
    private javax.swing.JTable depTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
