/*
 * English Dependencies Demo Project
 * Author: jcyuyi@gmail.com
 */

package englishdependenciesdemo;

import edu.stanford.nlp.ling.StringLabelFactory;
import edu.stanford.nlp.parser.ui.TreeJPanel;
import edu.stanford.nlp.trees.LabeledScoredTreeFactory;
import edu.stanford.nlp.trees.PennTreeReader;
import edu.stanford.nlp.trees.Tree;
import java.awt.BorderLayout;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.JLabel;

/**
 *
 * @author airjcy
 */
public class NLPTreePanel extends javax.swing.JPanel {

    /**
     * Creates new form NLPTreePanel
     */
    private String treeString;
    private TreeJPanel treeJPanel;
    public NLPTreePanel() {
        initComponents();
        add(BorderLayout.NORTH,new JLabel("Tree View:"));
         treeJPanel = new TreeJPanel();
         this.add(BorderLayout.CENTER,treeJPanel);
        setTreeString(treeString);
    }
    public void setTreeString(String aTreeString)
    {
        try {
            treeString = aTreeString;
            Tree tree = (new PennTreeReader(new StringReader(treeString), new LabeledScoredTreeFactory(new StringLabelFactory()))).readTree();
            treeJPanel.setTree(tree);   
            System.out.println("Set tree: " + aTreeString);
            repaint();
        } catch (Exception e) {
            System.err.println("Error to set tree string : " + e.getMessage());
            return;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
